// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCFRYfH7h4-0dcSZAbkJRDXOoIqu48KmU',
    appId: '1:628247406702:android:d5e85143ab773cbd8ede7f',
    messagingSenderId: '628247406702',
    projectId: 'tempo-3ac43',
    storageBucket: 'tempo-3ac43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0D2qCoYNp3NmOS6PdRxPzKsu8RPXdsBw',
    appId: '1:628247406702:ios:c936b1ec95c455468ede7f',
    messagingSenderId: '628247406702',
    projectId: 'tempo-3ac43',
    storageBucket: 'tempo-3ac43.firebasestorage.app',
    iosBundleId: 'com.tempo.tempo',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBpp2Oe9Tf9St5gT3pZhH-7B0wXP4N73k',
    appId: '1:628247406702:web:dc68fec35e89c8b08ede7f',
    messagingSenderId: '628247406702',
    projectId: 'tempo-3ac43',
    authDomain: 'tempo-3ac43.firebaseapp.com',
    storageBucket: 'tempo-3ac43.firebasestorage.app',
    measurementId: 'G-CL70DC3CQC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0D2qCoYNp3NmOS6PdRxPzKsu8RPXdsBw',
    appId: '1:628247406702:ios:c936b1ec95c455468ede7f',
    messagingSenderId: '628247406702',
    projectId: 'tempo-3ac43',
    storageBucket: 'tempo-3ac43.firebasestorage.app',
    iosBundleId: 'com.tempo.tempo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBpp2Oe9Tf9St5gT3pZhH-7B0wXP4N73k',
    appId: '1:628247406702:web:ff3a52e47ad6957f8ede7f',
    messagingSenderId: '628247406702',
    projectId: 'tempo-3ac43',
    authDomain: 'tempo-3ac43.firebaseapp.com',
    storageBucket: 'tempo-3ac43.firebasestorage.app',
    measurementId: 'G-V6CT9H05YM',
  );

}